numpy is a fundamental library for scientific computing in python .it provides support for arrays and matrices along with a collection of mathe matical function to operate on these data structures in this lessons,we will cover the basics of numpy,focusing on arrays and vectorized operations.m

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

#create arrays using numpy
#create a 1D array

arr1=np.array([1,2,3,45])
print(arr1)
print(type(arr1))
print(arr1.shape)

[ 1  2  3 45]
<class 'numpy.ndarray'>
(4,)


In [16]:
#1 D array

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)#1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [13]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
### 2D array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape


[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
###Identity matrix and array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)


Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

In [ ]:
######Attributes of numpy

arr=np.array([[1,2,3], [4,5,6],[5,7,9]])
print("shape:",arr.shape)
print("number of dimension",arr.ndim)
print("size(number of elemets)",arr.size)
print("data type",arr.dtype)
print("item size",arr.itemsize)


shape: (3, 3)
number of dimension 2
size(number of elemets) 9
data type int64
item size 8


In [21]:
###Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

###element wise addition
print('addition:',arr1+arr2)


##element wise substraction
print("subtraction:",arr1-arr2)


##element wise multiplication
print("multiplication:",arr1*arr2)


##element wise modulus
print("modulus:",arr1%arr2)

##element wise division
print("division:",arr1/arr2)

addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
modulus: [1 2 3 4 5]
division: [0.1 0.1 0.1 0.1 0.1]


In [26]:
##universal function
arr=np.array([2,3,4,5.6])
#square root
print("square:",np.sqrt(arr))

#exponential
print("expo:",np.exp(arr))

#sine

print("sin:",np.sin(arr))


##natural log
print("log:",np.log(arr))

square: [1.41421356 1.73205081 2.         2.36643191]
expo: [  7.3890561   20.08553692  54.59815003 270.42640743]
sin: [ 0.90929743  0.14112001 -0.7568025  -0.63126664]
log: [0.69314718 1.09861229 1.38629436 1.7227666 ]


In [37]:
## array slicing and indexing
arr=np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr[0][0]

arr[1][3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(8)

In [47]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [49]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [52]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [55]:
###modify array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [56]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [57]:
##practical application

#statistical concepts-normalization -> (to have a mean of 0 and standard deviation of 1)
data=np.array([1,2,3,4,5])
mean=np.mean(data)
std_dev=np.std(data)
normalized_data=(data-mean)/std_dev
print(normalized_data)




[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [59]:
##mean, mdedian,, mode
data=np.array([1,2,3,4,5,6,7,8,910])
mean=np.mean(data)
print("mean:",mean)

median=np.median(data)
print("median:",median)

std_dev=np.std(data)
print("stdandard devaition:",std_dev)

variance=np.var(data)
print("variance:",variance)

mean: 105.11111111111111
median: 5.0
stdandard devaition: 284.5793950706295
variance: 80985.43209876544


In [60]:
##logical operation
data =np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
data =np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])